# Cloud Run Cloud Build Manifest
steps:
  # 1. Build Docker container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/noble-beanbag-497411-m4/osintneoai-api:$COMMIT_SHA', '.']

  # 2. Push image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/noble-beanbag-497411-m4/osintneoai-api:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'osintneoai-api'
      - '--image=gcr.io/noble-beanbag-497411-m4/osintneoai-api:$COMMIT_SHA'
      - '--region=us-west2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=10001'
      - '--set-env-vars=BQ_PROJECT_ID=noble-beanbag-497411-m4,BQ_DATASET_ID=forensic_layers,BQ_TABLE_ID=genesis_ledger'

images:
  - 'gcr.io/noble-beanbag-497411-m4/osintneoai-api:$COMMIT_SHA'
