# Dockerfile for Official Kali Linux OSINT Toolsuite
FROM kalilinux/kali-rolling:latest

WORKDIR /osint_kali

# Update and install Kali OSINT, Recon, Network, and Forensics Toolsets
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 \
    python3-pip \
    git \
    curl \
    wget \
    nmap \
    hydra \
    recon-ng \
    whois \
    dnsenum \
    dnsrecon \
    theharvester \
    sherlock \
    spiderfoot \
    tshark \
    metasploit-framework \
    netcat-openbsd \
    nikto \
    sqlmap \
    && rm -rf /var/lib/apt/lists/*

# Expose Kali OSINT API / Bridge Port
EXPOSE 9090

CMD ["tail", "-f", "/dev/null"]
