import os
import shutil
import json
import csv

source_dir = r"C:\Users\HP\.gemini\antigravity\brain\71e7b1d1-f50b-477e-a713-942e8319b97d"
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(script_dir))
dest_dir = os.path.join(project_root, "briefings")
csv_path = os.path.join(project_root, "forensic_master_spreadsheet.csv")
js_out_path = os.path.join(project_root, "briefings_data.js")


print("--- OSINT Knowledge Base Setup ---")

# 1. Create directory if it doesn't exist
if not os.path.exists(dest_dir):
    os.makedirs(dest_dir)
    print(f"Created briefings directory at {dest_dir}")

# 2. Files to copy
briefing_files = [
    "anaheim_cyber_rico_briefing.md",
    "consolidated_forensic_timeline.md",
    "deepseek_import_summary.md",
    "federal_criminal_referral_briefing.md",
    "forensic_investigative_dossier.md",
    "google_dispute_legal_assessment.md",
    "hbnc_forensic_whistleblower_briefing.md",
    "lmihaf_treble_damages_exhibit.md",
    "marshall_wu_intelligence_report.md",
    "orange_county_coc_rico_pattern_map.md",
    "us_coc_forensic_pattern_master.md",
    "wechat_intelligence_report.md",
    "weekly_project_status_report.md"
]

copied_count = 0
for filename in briefing_files:
    src_file = os.path.join(source_dir, filename)
    dest_file = os.path.join(dest_dir, filename)
    if os.path.exists(src_file):
        shutil.copy2(src_file, dest_file)
        print(f"Copied {filename} successfully.")
        copied_count += 1
    else:
        print(f"Warning: Source file {filename} not found at {source_dir}")

print(f"Migration complete: copied {copied_count}/{len(briefing_files)} files.")

# 3. Read briefings to compile JSON
briefings_json = {}
for filename in briefing_files:
    dest_file = os.path.join(dest_dir, filename)
    if os.path.exists(dest_file):
        with open(dest_file, "r", encoding="utf-8") as f:
            content = f.read()
            title = filename.replace(".md", "").replace("_", " ").title()
            briefings_json[filename] = {
                "title": title,
                "content": content
            }

# 4. Read forensic_master_spreadsheet.csv
cases_list = []
if os.path.exists(csv_path):
    print(f"Parsing CSV file: {csv_path}")
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            cases_list.append(dict(row))
    print(f"Successfully loaded {len(cases_list)} cases.")
else:
    print(f"Warning: CSV file not found at {csv_path}")

# 5. Write to JS data file
with open(js_out_path, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by setup_kb.py. Do not edit directly.\n")
    f.write("const BRIEFINGS_DATA = ")
    json.dump(briefings_json, f, indent=2)
    f.write(";\n\n")
    f.write("const CASES_DATA = ")
    json.dump(cases_list, f, indent=2)
    f.write(";\n")

print(f"Successfully generated consolidated JS data file at: {js_out_path}")
